### ISSUE TITLE
Unknown IRC commands

### ISSUE THREAD

**Issue by mattoufoutu** [mattoufoutu/fatbotslim#18]
This issue lists all IRC codes reported as unknown by `fatbotslim` and their implementation status..

If you ever encounter one, re-run your bot with debug logging enabled (`-l DEBUG`), and comment this issue with the log line containing the said code (and any additional info you think could be of help to understand the meaning of the code).

Unknown codes:

- [x] `:barjavel.freenode.net 250 TestBotSlim :Highest connection count: 9560 (9559 clients) (1186567 connections received)`
- [x] `:orwell.freenode.net 332 TestBotSlim #channel :some channel topic here`
- [x] `:orwell.freenode.net 333 TestBotSlim #channel user!~user@unaffiliated/user 1428826477`
- [x] `:nick1!~name@ip NICK :nick2`

**Comment by mdeous** [comment]
added code `332` and `333`

**Comment by mdeous** [comment]
added `NICK`

**Comment by mdeous** [comment]
added `250`
